version: '3'
services:
  mongo:
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - /data/db
    ports:
      - 27017:27017
    restart: on-failure
    networks:
      - internal
    command: mongod
  server:
    build: ./server
    ports:
      - ${SERVER_PORT}:3000
    environment:
      - DATABASE_HOST=db
    depends_on:
      - mongo
